server:
  port: 9876
spring:
  application:
    name: convert-tools
logging:
  level:
    root: debug
    
    
  ######################## 自定义配置 #####################################

tdt:
  convert:
    charset: UTF-8   # 文件读取字符编码 GB2312 UTF-8 GBK
    # geoJson文件根路径
    input: E:\data\shp\test\input\osm
    # 输出路径
    output: E://data//shp//test//output
    type: 3
      ############ type 参数说明 ############
      #                                   #
      #            1: 84 转 百度           #
      #            2: 百度 转 84           #
      #            3: 84 转 高德           #
      #            4: 高德 转 84           #
      #            5: 百度 转 高德          #
      #            6: 高德 转 百度          #
      #                                   #
      #####################################